### PR TITLE
User/chwan/update api

### PR DESCRIPTION
**Pull request by mrsteamfist**
Updated the example to use the new Nuget package of webview - 0.9.488
Just a few API renames.

### CODE REVIEW

**Comment by Syul968** [comment]
Might want to update `ICoreWebView2Host` and `CoreWebView2Host` in readme as well.

**Comment by david-risney** [comment]
Yes, readme.md should be updated also. There's tables of API names and there's code snippets that need some updating.

**Comment by david-risney** [comment]
Looks good to me otherwise though =)

**Comment by mrsteamfist** [comment]
Fixed

**Comment by mrsteamfist** [comment]
Good call @peiche-jessica, fixed it.

**Comment by peiche-jessica** [comment]
> Good call @peiche-jessica, fixed it

@mrsteamfist Thanks for fixing the README.md! I believe we do have other usage in BrowserApp.cpp though.

**Comment by mrsteamfist** [comment]
Good catch, fixed here: https://github.com/MicrosoftEdge/WebView2Browser/pull/13

**Pull request merged**
